name = "cdn"
type = "javascript"

account_id = ""
workers_dev = true # or zone_id = "<ZONE ID>" if you have one
compatibility_date = "2022-07-23"

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"
